# Generated by Django 2.2 on 2019-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190413_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_problemsetter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
