# Generated by Django 2.1.7 on 2019-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=16)),
                ('internal_name', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('max_real_time', models.PositiveIntegerField(help_text='in milliseconds')),
                ('max_cpu_time', models.PositiveIntegerField(help_text='in milliseconds')),
                ('max_address_space', models.PositiveIntegerField(help_text='in kilobytes')),
                ('max_threads', models.PositiveIntegerField()),
            ],
        ),
    ]
