# Generated by Django 2.1.7 on 2019-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='max_address_space',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_cpu_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_real_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_threads',
        ),
    ]
