# Generated by Django 2.1.7 on 2019-03-30 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compete', '0002_auto_20190330_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('gcc', 'GNU C11 8.2.1'), ('g++', 'GNU C++17 8.2.1')], max_length=16)),
                ('status', models.CharField(choices=[('UK', 'Unknown'), ('IQ', 'In queue'), ('RG', 'Running'), ('CE', 'Compilation error'), ('AC', 'Accepted'), ('IG', 'Ignored')], default='UK', max_length=2)),
                ('cpu_used', models.PositiveIntegerField(help_text='in milliseconds')),
                ('memory_used', models.PositiveIntegerField(help_text='in kilobytes')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
