# Generated by Django 2.1.7 on 2019-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_auto_20190401_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
