# Generated by Django 2.1.7 on 2019-04-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compete', '0006_auto_20190401_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('CT', 'Classical contest'), ('TR', 'Training contest')], max_length=2)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='authored_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('official', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='legit',
            field=models.CharField(choices=[('CS', 'Submitted during contest'), ('US', 'Submitted during upsolving'), ('VC', 'Virtual contest submission')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='run',
            name='lang',
            field=models.CharField(choices=[('gcc', 'GNU C11 8.2.1'), ('g++', 'GNU C++17 8.2.1'), ('gcc-nostdlib', 'GNU C11 8.2.1 (nostdlib)'), ('g++-nostdlib', 'GNU C++17 8.2.1 (nostdlib)')], max_length=16),
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(related_name='participating', through='compete.ContestRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compete.Contest'),
        ),
    ]
