# Generated by Django 2.1.7 on 2019-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0008_auto_20190405_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestregistration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
