# Generated by Django 2.1.7 on 2019-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0009_auto_20190406_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='statement',
        ),
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
