# Generated by Django 2.2 on 2019-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0011_auto_20190406_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
