# Generated by Django 2.2 on 2019-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0013_userproblemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestregistration',
            name='status',
            field=models.CharField(db_index=True, default='OK', max_length=2),
        ),
        migrations.AddField(
            model_name='problem',
            name='visibility',
            field=models.CharField(choices=[('AA', 'Make visible for everyone when contest starts'), ('AR', 'Make visible for contest participants when contest starts'), ('VA', 'Visible for everyone'), ('VR', 'Visible for contest participants'), ('IN', 'Invisible')], default='AA', max_length=2),
        ),
    ]
