# Generated by Django 2.2 on 2019-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0015_auto_20190411_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestregistration',
            old_name='score1',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='contestregistration',
            name='status',
            field=models.CharField(choices=[('OK', 'Registered'), ('PD', 'Registration pending'), ('RJ', 'Registration rejected')], db_index=True, default='OK', max_length=2),
        ),
    ]
