# Generated by Django 2.2 on 2019-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0017_auto_20190412_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration',
            field=models.CharField(choices=[('OP', 'Open registration'), ('MD', 'Moderated registration'), ('IN', 'Only by invites')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='contest',
            name='visible',
            field=models.BooleanField(blank=True, default=True, help_text='Is this contest visible to non-participants?'),
        ),
        migrations.AlterField(
            model_name='run',
            name='lang',
            field=models.CharField(choices=[('gcc', 'GNU C11 8.2.1'), ('g++', 'GNU C++17 8.2.1'), ('gcc-nostdlib', 'GNU C11 8.2.1 (nostdlib)'), ('g++-nostdlib', 'GNU C++17 8.2.1 (nostdlib)'), ('brainfuck', 'Brainfuck')], max_length=16),
        ),
    ]
