# Generated by Django 2.2 on 2019-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0019_auto_20190415_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coauthors',
            field=models.TextField(default=''),
        ),
    ]
