# Generated by Django 2.2 on 2019-04-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0020_auto_20190415_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coauthors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
