# Generated by Django 2.2 on 2019-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0022_auto_20190416_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
