# Generated by Django 2.2 on 2019-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0023_problem_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
