# Generated by Django 2.2 on 2019-04-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compete', '0024_auto_20190417_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField(default=0)),
                ('old_deviation', models.IntegerField(default=0)),
                ('old_volatility', models.FloatField(default=0)),
                ('new_rating', models.IntegerField(default=0)),
                ('new_deviation', models.IntegerField(default=0)),
                ('new_volatility', models.FloatField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
