# Generated by Django 2.2 on 2019-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0025_ratingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='rating_applied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
