# Generated by Django 2.2 on 2019-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190413_0959'),
        ('compete', '0027_auto_20190420_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='posts',
            field=models.ManyToManyField(related_name='contests', to='blog.Post'),
        ),
    ]
