# Generated by Django 2.2 on 2019-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0028_contest_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='contests', to='blog.Post'),
        ),
    ]
